### ISSUE TITLE
Problems with running the app service

### ISSUE THREAD

**Issue by Adapter668** [microsoft/InnerEye-Inference#42]
I updated the InnerEye-Inference project to the newest version and now it doesn't run at all - I'm using the same commands that worked before, which are mentioned in README.md

```shell
az login --use-device-code
az webapp up --sku S1 --name inferenceapp --subscription <subscription_name> -g InnerEyeInference --location <location>
```

Which gives me the output:
Could not auto-detect the runtime stack of your app.
HINT: Are you in the right folder?
For more information, see 'https://go.microsoft.com/fwlink/?linkid=2109470'

I created set_environment.sh with all variables set with correct data (they have worked the whole time for inference).

Do you have any idea what could be the problem here and how we could solve it? (for example, should we define any additional path in the configs?)

**Comment by peterhessey** [comment]
#### The problem

So turns out that the `az webapp up` command [checks for the existence of a `requirements.txt` file](https://github.com/Azure/app-service-linux-docs/blob/master/AzWebAppUP/runtime_detection.md#python-detection-logic) as part of the python runtime checks, even if one isn't needed. This file was removed in the most recent commit adjusting how the environments work when all pip dependencies were placed directly into `environment.yml`. 

#### Temporary Fix

You can quickly circumvent this issue by creating an empty `requirements.txt` file in the head of the directory (e.g. by running `touch requirements.txt` if you are running a bash shell). The `az webapp up` command will then work as expected.

#### Long-term fix

A blank `requirements.txt` file containing a comment explaining its existence could be added to the repo permanently. Or if we want to be particularly clean about it, the `create_and_lock_environment.sh` script could be configured to export the pip requirements into the `requirements.txt` file and then point the `environment.yml` file towards it.
